"""
Auto-generated LEAN algorithm for strategy: Ema Crossover Long
Strategy ID: mNDy8QxK9ETdeRl32inE

Generated by vibe-trade translator.
"""

from AlgorithmImports import *
import os


class EmaCrossoverLongAlgorithm(QCAlgorithm):
    """Trading algorithm for Ema Crossover Long."""

    def Initialize(self):
        """Initialize the algorithm."""
        # Don't set dates in live mode
        if not self.LiveMode:
            self.SetStartDate(2024, 1, 1)
            self.SetEndDate(2024, 12, 31)

        self.SetCash(100000)

        # Setup symbol
        # Backtest mode: use standard LEAN crypto data
        self.symbol = self.AddCrypto("BTCUSD", Resolution.Minute, Market.GDAX).Symbol

        # Initialize indicators
        self.ema_fast = self.EMA(self.symbol, 20, Resolution.Minute)
        self.ema_slow = self.EMA(self.symbol, 50, Resolution.Minute)

        # State tracking
        self.entry_triggered = False
        self.bars_since_entry = 0

        self.Log(f"Strategy initialized: Ema Crossover Long")
        self.Log(f"Symbol: {self.symbol}")

    def OnData(self, data):
        """Process new data."""
        if self.symbol not in data or data[self.symbol] is None:
            return

        bar = data[self.symbol]

        # Check if indicators are ready
        if not self._indicators_ready():
            return

        # Check exits first (if in position)
        if self.Portfolio[self.symbol].Invested:
            self.bars_since_entry += 1
            # Exit condition 1
            if self.ema_fast.Current.Value < self.ema_slow.Current.Value:
                self.Liquidate(self.symbol)

        # Check entries (if not in position)
        if not self.Portfolio[self.symbol].Invested:
            # Entry condition 1
            if self.ema_fast.Current.Value > self.ema_slow.Current.Value:
                self.SetHoldings(self.symbol, 0.95)

    def _indicators_ready(self) -> bool:
        """Check if all indicators are ready."""
        return self.ema_fast.IsReady and self.ema_slow.IsReady

    def OnOrderEvent(self, orderEvent):
        """Handle order events."""
        if orderEvent.Status == OrderStatus.Filled:
            direction = "BUY" if orderEvent.FillQuantity > 0 else "SELL"
            self.Log(f"{direction} {abs(orderEvent.FillQuantity)} @ ${orderEvent.FillPrice:.2f}")
            if orderEvent.FillQuantity > 0:
                self.entry_triggered = True
                self.bars_since_entry = 0
            else:
                self.entry_triggered = False

    def OnEndOfAlgorithm(self):
        """Algorithm ended."""
        self.Log(f"Final portfolio value: ${self.Portfolio.TotalPortfolioValue:,.2f}")